language: java
install: true

os: linux
jdk:
  - openjdk8
  - openjdk11
  - oraclejdk11

env:
  - CI=true

script:
  - gradle buildPlugin

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/