build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
  # complexity: 2
  # LongParameterList: 1
  # style: 1
  # comments: 1

config:
  validation: true
  warningsAsErrors: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

formatting:
  FinalNewline:
    active: true
    insertFinalNewLine: false
  Indentation:
    active: false
    autoCorrect: true
    indentSize: 4
    continuationIndentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 160
  NoWildcardImports:
    active: true
  PackageName:
    active: false
  ParameterListWrapping:
    active: true
    autoCorrect: true
    indentSize: 4

naming:
  active: true
  PackageNaming:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
    packagePattern: '[a-z_]+(\.[a-z][A-Za-z0-9]*)*'

performance:
  active: true
  SpreadOperator:
    active: false

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 160
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    active: false